# Generated by Django 3.2.7 on 2021-11-18 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20211007_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tel',
            field=models.CharField(default=0, max_length=11, verbose_name='Data'),
            preserve_default=False,
        ),
    ]
