# Generated by Django 3.2.7 on 2021-11-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='professional',
            field=models.BooleanField(default=False),
        ),
    ]
