# Generated by Django 3.2.7 on 2021-12-30 21:18

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20211203_1223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': [django.db.models.functions.text.Upper('name')]},
        ),
    ]
