# Generated by Django 3.2.7 on 2021-12-30 21:19

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': [django.db.models.functions.text.Upper('first_name')]},
        ),
    ]
