# Generated by Django 3.2.7 on 2022-02-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_master',
            field=models.BooleanField(default=False),
        ),
    ]
