# Generated by Django 3.2.7 on 2021-09-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Preço'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo'),
        ),
    ]
