# Generated by Django 3.2.7 on 2021-09-29 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_auto_20210924_1741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='weekday',
        ),
    ]
