# Generated by Django 3.2.7 on 2021-09-29 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0003_remove_schedule_weekday'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(choices=[('0', 'Domingo'), ('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
