# Generated by Django 3.2.7 on 2021-09-29 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0004_schedule_weekday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appdate',
            field=models.CharField(max_length=10, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='apphour',
            field=models.CharField(max_length=5, verbose_name='Horário'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientss', to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registrations.payment', verbose_name='Pagamento'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='procedure',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registrations.procedure', verbose_name='Procedimento'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='professionalss', to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registrations.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='total',
            field=models.IntegerField(blank=True, null=True, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='bugbounty',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='bugbounty',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='bugbounty',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='bugbounty',
            name='solved',
            field=models.BooleanField(default=False, verbose_name='Resolvido'),
        ),
        migrations.AlterField(
            model_name='bugbounty',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Criado em.'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='daydate',
            field=models.CharField(max_length=10, verbose_name='Data do Feriado'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='professional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='dayoff',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Motivo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='discount',
            field=models.FloatField(blank=True, null=True, verbose_name='Desconto'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='tax',
            field=models.FloatField(blank=True, null=True, verbose_name='Acréscimo'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='begin',
            field=models.CharField(max_length=5, verbose_name='Inicio do Atendimento'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='end',
            field=models.CharField(max_length=5, verbose_name='Final do Atendimento'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='interval',
            field=models.IntegerField(verbose_name='Intervalo(minutos)'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(choices=[('0', 'Domingo'), ('1', 'Segunda-feira'), ('2', 'Terça-feira'), ('3', 'Quarta-feira'), ('4', 'Quinta-feira'), ('5', 'Sexta-feira'), ('6', 'Sábado')], default=0, max_length=1, verbose_name='Dia da Semana'),
        ),
        migrations.AlterField(
            model_name='status',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome'),
        ),
    ]
