# Generated by Django 3.2.7 on 2021-09-30 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_auto_20210929_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.CharField(choices=[('0', 'Segunda-feira'), ('1', 'Terça-feira'), ('2', 'Quarta-feira'), ('3', 'Quinta-feira'), ('4', 'Sexta-feira'), ('5', 'Sábado'), ('6', 'Domingo')], default=0, max_length=1, verbose_name='Dia da Semana'),
        ),
    ]
