# Generated by Django 3.2.7 on 2021-11-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_appointment_payed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payed',
            field=models.BooleanField(default=False, verbose_name='Pago'),
        ),
    ]
