# Generated by Django 3.2.7 on 2021-11-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_alter_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='payed',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='N', max_length=1, verbose_name='Pago'),
        ),
    ]
