# Generated by Django 3.2.7 on 2021-11-30 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0011_alter_appointment_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Nome do Procedimento'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='price',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Preço R$'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tempo (minutos)'),
        ),
    ]
