# Generated by Django 3.2.7 on 2021-11-30 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0012_auto_20211130_1252'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BugBounty',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='payment',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
