# Generated by Django 3.2.7 on 2021-12-01 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0013_auto_20211130_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterappointment', to=settings.AUTH_USER_MODEL, verbose_name='Master'),
        ),
        migrations.AddField(
            model_name='dayoff',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterdayoff', to=settings.AUTH_USER_MODEL, verbose_name='Master'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterschedule', to=settings.AUTH_USER_MODEL, verbose_name='Master'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='master',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mastersprocedure', to=settings.AUTH_USER_MODEL, verbose_name='Master'),
        ),
    ]
