# Generated by Django 3.2.7 on 2021-12-01 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registrations', '0014_auto_20211201_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('tel', models.CharField(max_length=11, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='Nome')),
                ('email', models.CharField(blank=True, max_length=60, null=True, verbose_name='E-mail')),
                ('obs', models.TextField(blank=True, null=True, verbose_name='Obervações')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='Criado em.')),
                ('master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='masterclient', to=settings.AUTH_USER_MODEL, verbose_name='Master')),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clientss', to='registrations.client', verbose_name='Cliente'),
        ),
    ]
