# Generated by Django 3.2.7 on 2021-12-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_auto_20211201_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='price',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço R$'),
        ),
    ]
