# Generated by Django 3.2.7 on 2021-12-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0018_auto_20211201_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='birth',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Data de nascimento'),
        ),
    ]
