# Generated by Django 3.2.7 on 2021-12-01 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0019_client_birth'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='dayoff',
            old_name='active',
            new_name='is_active',
        ),
        migrations.RenameField(
            model_name='schedule',
            old_name='active',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='client',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
