# Generated by Django 3.2.7 on 2021-12-30 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0020_auto_20211201_1810'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',)},
        ),
    ]
