# Generated by Django 3.2.7 on 2021-12-30 20:54

from django.db import migrations
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0021_alter_client_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': [django.db.models.functions.text.Lower('name')]},
        ),
    ]
