# Generated by Django 3.2.7 on 2022-02-23 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0027_alter_appointment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='is_shared',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], default='S', max_length=1, verbose_name='Compartilhar na Agenda Online'),
        ),
    ]
