# Generated by Django 4.0.3 on 2022-03-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0029_alter_appointment_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appbegin',
            field=models.TimeField(blank=True, null=True, verbose_name='Inicio Atendimento'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='append',
            field=models.TimeField(blank=True, null=True, verbose_name='Final Atendimento'),
        ),
    ]
