# Generated by Django 4.0.3 on 2023-09-06 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0031_alter_procedure_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='time',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Tempo (minutos)'),
        ),
    ]
